### ISSUE TITLE
Questions: Ticks state, Event data ownership, Pause & Play, Enterpolate, Nightly.

### ISSUE THREAD

**Issue by iggyzuk** [Gavin-Niederman/saunter#2]
Very cool library! I'm enjoying working with it so far.

I have some thoughts and questions, please note I'm fairly new to Rust.

1. As I understand it, the game state should be in the `Listener`. But I'm confused about what the `Tick` is supposed to contain. Is it also the entire game state, or just the bits we need for rendering? I would imagine just the rendering bits since `Ticks` are _lerp-able_. I guess you could return the same state that the `Listener` is holding but then you would need to copy it which could be expensive if the state is massive.

2. Can events pass ownership of the data inside them to the `Listener`?  I tried making the following event, but found no way to take ownership of the data as it's passed by a mutable reference. Which isn't the end of the world, I can always pass a request to do something, but then the `Listener` has to do more work.

```rust
enum GameEvent {
    Build(Building),
}
```

3. Is there a way to pause the loop? Doesn't look like it, maybe a nice thing for the future. It would probably require two more variants to the `saunter::event::Event` for `Pause` and `Play`.

4. Is `enterpolate` a real technical term? Likely a typo for `interpolate`.

5. Due to `#![feature(associated_type_defaults)]` I have to use `cargo +nightly run`, is this right?

**Comment by Gavin-Niederman** [comment]
Hi thanks for taking the time to ask these questions!

I'm going to answer question 4 and 5 first because they are the easiest. 

4. Yes that is a typo, I shudder to think of how many times I have misspelled that.
5. That line is not necessary and I am removing it now. I'm not sure how I missed it in the first place! So no you wont need to build with an unstable cargo tool chain.

I will answer the others in order now.

1. Your assumptions are correct, I made it so that you can store whatever you want in a tick because you probably won't want to store the entire state, for the performance reasons you mentioned. I do think that I made that too vague so I will improve the documentation.
2. After I update the crate the tick function will be passed a ``Vec<Event<E>>`` instead of a ``&mut Vec<Event<E>>``. This was another mistake.
3. Currently there is no way but I will try to add one!

**Comment by iggyzuk** [comment]
Nice one! Thanks for clarifying.

I have another question – how would you validate player actions that depend on the game state? For example the game state can have fields for resources, and the player is trying to construct a building that requires 4 wood and 3 stone. Currently the `Listener` owns the game state. Do you think we need another `Arc<RwLock<GameState>>` that would be returned from `Loop::init()`? Or should the `Ticks` return the state that the inputs depend on?

**Comment by Gavin-Niederman** [comment]
In most game engines the player is part of the game state. The way I would go about this is to write an entity component system for this hypothetical game. With that it's pretty simple to implement all in the listener.

- have a player entity with a Player component, and a resources entity with a Resources component to store what is available to the player (You could also store available resources in the player component).
- have a system that gets the Player component of the player and the Resources component of the resources uses the events passed to the listener to see what the player is doing. If the player is placing a building it would check if they had enough resources and act accordingly.

For rendering with an ecs you would want to have a camera entity.

I'm currently working on an example game engine using Saunter so when I finish it should hopefully answer some questions.

**Comment by iggyzuk** [comment]
True, ECS makes a lot of sense here.

- But is there a way to check that the player has enough resources before sending a `Build` event? Since from what I understand the inputs + rendering happens on the main thread, and the state lives on another, you can't just read the state.

- I guess the `Tick` does need to return a lot of the game state, player component and all the resources, which can be used for inputs as well as the rendering, e.g. if you press on the building to see what kind of resources it's holding. It seems like a lot of state needs to be copied over from `Listener` to the `Tick` each tick, do you think this is fine from the perspective of performance?

You know, it would be amazing to get a more complex example in the library ;)

**Comment by Gavin-Niederman** [comment]
The events should be captured one the main thread, but handled in the loop thread.

The way I intended for events to work is that, for example with winit, you capture the events with an ``event_loop`` and send them to the Saunter ``Loop``. Just the base ``winit::event::Event<'_, ()>``.

If you want to use a custom event type with the ``Build`` event you were talking about that should be handled on the loop side of things. 

The rendering thread should have nothing to do with how events are handled so that it will be as fast as possible, and so that you don't have to send much of the state in a ``Tick``. The render thread should be just that, a **render** thread. This pattern can be seen in the winit example.
